//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dka.AspNetCore.BasicWebApp.Resources.Views.About {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dka.AspNetCore.BasicWebApp.Resources.Views.About.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сеа ад лаборе интеллегебат. Цу еиус цлита долорум ест, яуандо ехерци ут усу. Яуандо еирмод ан ест, аццумсан адверсариум хас ин, фиерент делецтус суавитате не еос. Пер не сингулис рецусабо продессет, юсто либер тинцидунт нец ет, нец ет яуаеяуе санцтус цонсететур..
        /// </summary>
        internal static string In_enim_justo__rhoncus_ut__imperdiet_a__venenatis_vitae__justo__Nullam_dictum_felis_eu_pede_mollis_pretium__Integer_tincidunt__Cras_dapibus__Vivamus_elementum_semper_nisi__Aenean_vulputate_eleifend_tellus__Aenean_leo_ligula__porttitor_eu__consequat_vitae__eleifend_ac__enim__Aliquam_lorem_ante__dapibus_in__viverra_quis__feugiat_a__tellus_ {
            get {
                return ResourceManager.GetString(@"In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лорем ипсум долор сит амет, те яуот цорпора хис. Не алияуам цонвенире вим, ат меи яуис иудицо маиестатис. Пертинах иудицабит репримияуе нец еа. Ид аудиам индоцтум меа, яуас алияуид цетерос но еам..
        /// </summary>
        internal static string Lorem_ipsum_dolor_sit_amet__consectetuer_adipiscing_elit__Aenean_commodo_ligula_eget_dolor__Aenean_massa__Cum_sociis_natoque_penatibus_et_magnis_dis_parturient_montes__nascetur_ridiculus_mus__Donec_quam_felis__ultricies_nec__pellentesque_eu__pretium_quis__sem__Nulla_consequat_massa_quis_enim__Donec_pede_justo__fringilla_vel__aliquet_nec__vulputate_eget__arcu_ {
            get {
                return ResourceManager.GetString(@"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот проект является результатом изучения ASP.NET Core 3.0.
        /// </summary>
        internal static string This_project_is_a_result_of_study_of_ASP_NET_Core_3_0 {
            get {
                return ResourceManager.GetString("This project is a result of study of ASP.NET Core 3.0", resourceCulture);
            }
        }
    }
}
